# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R1MwsU-fOEJa7x95nnNJAs1tpNHbsG2k
"""

class ATM:
    def __init__(self):
        self.users = {
            '123456': {'pin': '1234', 'balance': 5000, 'transactions': []},
            '987654': {'pin': '5678', 'balance': 10000, 'transactions': []}
        }
        self.current_user = None

    def authenticate(self, card_number, pin):
        if card_number in self.users:
            if self.users[card_number]['pin'] == pin:
                self.current_user = card_number
                return "Login successful!"
            else:
                return "Invalid PIN."
        else:
            return "Invalid card number."

    def main_menu(self, choice):
        if choice == '1':
            return self.view_balance()
        elif choice == '2':
            amount = float(input("Enter amount to deposit (INR): "))
            self.deposit_money(amount)
            return self.ask_see_balance()
        elif choice == '3':
            amount = float(input("Enter amount to withdraw (INR): "))
            self.withdraw_money(amount)
            return self.ask_see_balance()
        elif choice == '4':
            target_card = input("Enter the target card number: ")
            amount = float(input("Enter amount to transfer (INR): "))
            self.transfer_money(target_card, amount)
            return self.ask_see_balance()
        elif choice == '5':
            return self.transaction_history()
        elif choice == '6':
            self.current_user = None
            return "Thank you for using the ATM. Goodbye!"
        else:
            return "Invalid choice. Please try again."

    def view_balance(self):
        balance = self.users[self.current_user]['balance']
        return f"Your current balance is: ₹{balance}"

    def deposit_money(self, amount):
        self.users[self.current_user]['balance'] += amount
        self.users[self.current_user]['transactions'].append(f"Deposited: ₹{amount}")
        print(f"₹{amount} deposited successfully.")

    def withdraw_money(self, amount):
        if amount <= self.users[self.current_user]['balance']:
            self.users[self.current_user]['balance'] -= amount
            self.users[self.current_user]['transactions'].append(f"Withdrew: ₹{amount}")
            print(f"₹{amount} withdrawn successfully.")
        else:
            print("Insufficient balance.")

    def transfer_money(self, target_card, amount):
        if target_card in self.users and amount <= self.users[self.current_user]['balance']:
            self.users[self.current_user]['balance'] -= amount
            self.users[target_card]['balance'] += amount
            self.users[self.current_user]['transactions'].append(f"Transferred ₹{amount} to {target_card}")
            self.users[target_card]['transactions'].append(f"Received ₹{amount} from {self.current_user}")
            print(f"₹{amount} transferred successfully.")
        else:
            print("Transfer failed. Check the card number and balance.")

    def transaction_history(self):
        return "Transaction History:\n" + "\n".join(self.users[self.current_user]['transactions'])

    def ask_see_balance(self):
        choice = input("Enter 1 to see balance or 0 to go back to the main menu: ")
        if choice == '1':
            print(self.view_balance())
            return self.ask_quit_or_menu()
        else:
            return self.show_menu()

    def ask_quit_or_menu(self):
        choice = input("Enter 1 to quit or 0 to go back to the main menu: ")
        if choice == '1':
            self.current_user = None
            return "Thank you for using the ATM. Goodbye!"
        else:
            return self.show_menu()

    def show_menu(self):
        print("\nMain Menu:")
        print("1. View Balance")
        print("2. Deposit Money")
        print("3. Withdraw Money")
        print("4. Transfer Money")
        print("5. Transaction History")
        print("6. Quit")
        choice = input("Choose an option: ")
        return self.main_menu(choice)


atm = ATM()

# Main menu loop
while True:
    card_number = input("Enter your card number: ")
    pin = input("Enter your PIN: ")
    message = atm.authenticate(card_number, pin)
    print(message)

    if atm.current_user:
        while True:
            response = atm.show_menu()
            if response == "Thank you for using the ATM. Goodbye!":
                break
            else:
                print(response)
    else:
        continue